package stratempo

var digitsMap = map[string]int{
	"zero":        0,
	"un":          1,
	"uno":         1,
	"due":         2,
	"tre":         3,
	"trè":         3,
	"quattro":     4,
	"cinque":      5,
	"sei":         6,
	"sette":       7,
	"otto":        8,
	"nove":        9,
	"dieci":       10,
	"undici":      11,
	"dodici":      12,
	"tredici":     13,
	"quattordici": 14,
	"quindici":    15,
	"sedici":      16,
	"diciassette": 17,
	"diciotto":    18,
	"diciannove":  19,
	"venti":       20,
	"vent":        20,
	"trenta":      30,
	"trent":       30,
	"quaranta":    40,
	"quarant":     40,
	"cinquanta":   50,
	"cinquant":    50,
	"sessanta":    60,
	"sessant":     60,
	"settanta":    70,
	"settant":     70,
	"ottanta":     80,
	"ottant":      80,
	"novanta":     90,
	"novant":      90,
	"cento":       100,
	"cent":        100,
	// "mille":       1000,
}
